### ISSUE TITLE
Image Library needs some love

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#101]
While looking at https://github.com/backdrop-contrib/gin/issues/95 I see that the image library browser needs some love. See screenshots in that issue, and also noting that dark mode also has some core CSS poking through.

EDIT: Changes made on this issue include:
 - Overriding the image library to use the "medium" format instead of "thumbnail"
 - Displaying a square/cropped version of the image, which changes to a small view of the full image on hover
 - Adjusting styles for images and selections
 - Greying out non-selected images when a selection is made (yay `:has()`!)

**Comment by laryn** [comment]
I made a first pass at some improvements here, not yet including the pager (which has it's own issue linked above):

![CleanShot 2024-01-10 at 16 57 32@2x](https://github.com/backdrop-contrib/gin/assets/871421/1f9f82ea-4c6d-4993-9c01-20b72a1e8376)

**Comment by stpaultim** [comment]
I am going to reopen this issue, because I think this is related. After updating GIN on my test site, I'm seeing this CSS poking through with a border that shouldn't be there.

![image](https://github.com/backdrop-contrib/gin/assets/3144571/5bd4d8a2-f617-4b3e-aac5-87c10f97c466)

@laryn 

I don't remember seeing this before.

**Comment by olafgrabienski** [comment]
@stpaultim Do you mean the blue outline? This is only visible when the field has `focus`. I see this also with Gin 1.x-3.0.0-alpha8.

**Comment by laryn** [comment]
That does look like the `:focus` outline, which is important for accessibility so keyboard navigators know where they are on the page.

**Comment by stpaultim** [comment]
I'll do some additional testing. I didn't notice this before and suddenly it was very obvious.

**Comment by laryn** [comment]
I made a minor adjustment here, and closing for now -- reopen if I've missed something.
![CleanShot 2024-02-16 at 11 18 17@2x](https://github.com/backdrop-contrib/gin/assets/871421/83b57d87-e0a5-447e-a3da-0e4491ace569)
