### ISSUE TITLE
List views page without disabled style

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#104]
Disabled views on the Views list page (`admin/structure/views`) look the same as enabled views. It would be nice to differentiate between them, so that disabled views are less prominent.

See the following screenshot where the "Promoted cards" view is disabled:

![image](https://github.com/backdrop-contrib/gin/assets/14188307/7b94ff87-faa6-41cc-93b4-9378a79bba89)

**Comment by olafgrabienski** [comment]
Maybe change opacity? Something like this:

```
table.views-list tr.disabled {
  opacity: 0.5;
}
table.views-list tr.disabled:hover,
table.views-list tr.disabled:focus-within {
  opacity: 0.85;
}
```

**Comment by laryn** [comment]
@olafgrabienski I was just thinking about this the other day! I think Drupal has disabled Views separated with a different table and its own header, which makes things pretty clear, and could be an alternative (core) issue which would improve it for all admin themes.

But if we stick with visuals that Gin can provide, I think opacity might be problematic from an accessibility/contrast point of view. I'll think on it a bit further. There is a custom property/variable for disabled background color, but I think it's not typically used on such a large swath of screen. Any thoughts on this?

![CleanShot 2024-01-12 at 11 08 51@2x](https://github.com/backdrop-contrib/gin/assets/871421/b82f3d2c-bdb1-401f-a40a-346c752f0860)

![CleanShot 2024-01-12 at 11 13 07@2x](https://github.com/backdrop-contrib/gin/assets/871421/4aef86a0-7dc8-4b0c-90e3-650d969b37f3)

**Comment by olafgrabienski** [comment]
Thanks for your reply, @laryn! I like the idea to put disabled views in a different table with an own header. There is even a core issue where the idea is discussed: https://github.com/backdrop/backdrop-issues/issues/4519 (needs more feedback, btw)

In the meatime, _some_ visual indication for disabled views would definitely be helpful. When I disabled a view the other day, the first impression was it hadn't been disabled at all. And the variable for disabled background color would be better than nothing, in my opinion. (If it's feasible to adapt it a bit for larger spaces, even better.)

When I posted the `opacity` approach, I was aware of possible contrast issues. That's why I added the `:hover` and `:focus-within` part. It should make sure the contrast is high enough when you hover over (or tab into) a disabled row. Not sure if something like this is an eligible approach.

**Comment by laryn** [comment]
I am making a [previous commit](https://github.com/backdrop-contrib/gin/commit/2679fda9c7bdca163b4c5c8fbae8facaf9328d50) more broadly applicable for this use case, at least for now so there is a visual distinction on the disabled rows of tables generally.
