### ISSUE TITLE
"Show all columns" link doesn't work

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#106]
On the Manage content page (`admin/content`) there is a "Show all columns" link. The title attribute describes the link as follows:

> Toggle visibility of table cells, that were hidden to make the table fit within a small screen.

For me, the link is visible all of the time, no matter how wide the screen is. And if the screen is too small to show all table columns, the link doesn't work anyway.

Screenshot:

<img src="https://github.com/backdrop-contrib/gin/assets/14188307/48801fe5-ba22-45ef-81a1-227c552487da" width="600">

**Comment by laryn** [comment]
@olafgrabienski Are you able to test the PR I just linked here? It just adds a bit of CSS that was in Seven to show and hide various table-related elements at specific breakpoints.

**Comment by olafgrabienski** [comment]
@laryn Thanks for the PR! I've just tested it on a local site, and it works as expected: With the PR, the "Show all columns" link is only visible on narrower screens. When I use it, all columns are displayed, and the link text changes to "Hide less important columns" (works as well).

**Comment by laryn** [comment]
Thanks @olafgrabienski -- merged.
