### ISSUE TITLE
Views bulk action form

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#11]
In Gin this is moved to the bottom of the View:

![image](https://github.com/laryn/tonic/assets/871421/6c77c78b-1fd8-4adf-949a-26e6ca79b34b)

**Comment by laryn** [comment]
![image](https://github.com/laryn/tonic/assets/871421/19a4421a-2988-41c2-84b2-7a64e10b15b5)

**Comment by laryn** [comment]
Re-opening after reverting the name to Gin.

**Comment by saschaeggi** [comment]
Migrated with f6a93ef
