### ISSUE TITLE
Clean up References Dialog edit modal styling

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#114]
In the content edit form, when I add or edit _another_ content item using [References Dialog](https://github.com/backdrop-contrib/references_dialog), the sidebar panel on the primary content edit form is rendered above the References Dialog overlay, making it unclear to which form the sidebar belongs (see screenshots below).

Changing `z-index` for the sidebar from `103` to `100` fixes the issue for me:

```
.gin--edit-form .edit-form--sidebar.page-wrapper .layout-region-node-secondary {
  z-index: 100;
}
```

(Some parts of commit https://github.com/backdrop-contrib/gin/commit/254bdb792d0a0301ea06e8660ce85b66df208358 look related.)

**Expected behavior:**
![image](https://github.com/backdrop-contrib/gin/assets/14188307/9e6372fa-7f0f-46ab-adee-ad081189a725)

**Actual behavior:**
![image](https://github.com/backdrop-contrib/gin/assets/14188307/39d8f031-7f1d-484e-a499-de7a4646075a)

**Comment by laryn** [comment]
@olafgrabienski Is this sidebar z-index still an issue with the most recent code? It does look like References Dialog needs some cleanup as well, in terms of dialogs (size, placement, etc.)

Other notes about References Dialog:

- Maybe we need to make sure the "sidebar edit details" don't apply within modals, it's messing the bottom of the modal edit display
- There are some icons in use with RD that should be adjusted to use SVG and make sure they work with dark mode
![CleanShot 2024-03-25 at 16 34 56@2x](https://github.com/backdrop-contrib/gin/assets/871421/7af6724a-2ae9-4a93-b4c7-af1dbc999e07)
- RD should make modals display better in terms of size and placement (they display poorly with Seven as well)

**Comment by olafgrabienski** [comment]
Just tested: with the current code the issue is fixed for me, great!

And I agree, the display of [References Dialog](https://github.com/backdrop-contrib/references_dialog) could need some love.

> Maybe we need to make sure the "sidebar edit details" don't apply within modals (...)

Are you referring to the vertical tabs (Publishing actions, Authoring information, ...)? Those should stay, in my opinion, but I'm sure they can be styled in a more pleasant way.

**Comment by laryn** [comment]
Closing for now as things are looking a lot better. 
![CleanShot 2024-09-13 at 23 26 07@2x](https://github.com/user-attachments/assets/927b25f4-f23f-4f64-a769-dc465f9ebb68)
