### ISSUE TITLE
Admin bar, Language switcher alignment

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#118]
The Language switcher in the Admin bar doesn't have the same vertival alignment as the other components – see screenshot below.

The reason could be that the element `<span class="locale">` isn't addressed by the CSS padding definition around https://github.com/backdrop-contrib/gin/blob/1.x-3.x/dist/css/layout/gin_admin_bar.css#L60.

(To make the Language switcher available, enable the Locale module and add a Language to the site.)

**Screenshot:**

<img src="https://github.com/backdrop-contrib/gin/assets/14188307/b929f1ff-5099-4c47-b23b-9289b8640f95" width="500">

**Comment by laryn** [comment]
I'm making an adjustment here and including the "translate" icon from https://phosphoricons.com, licensed under the MIT license.

![CleanShot 2024-03-09 at 15 06 05@2x](https://github.com/backdrop-contrib/gin/assets/871421/dd516bc1-5c3f-41ac-b287-660fa0d182b4)
