### ISSUE TITLE
Too little margin between Admin bar and Breadcrumb

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#119]
After an update to Gin alpha 10, I noticed a small visual regression on my Backdrop sites: The margin between Admin bar and Breadcrumb is smaller than before – see screenshot below.

The following CSS definition from `gin/dist/css/components/toolbar_secondary.css` that apply to the `<header>` element, which contains the Breadcrumb, might be related:

```
.gin-secondary-toolbar {
  z-index: 100;
  position: relative;
  display: flex;
  align-items: center;
  padding-top: var(--gin-spacing-xs);
  padding-bottom: var(--gin-spacing-xs);
  margin-top: -1px;
  height: var(--gin-toolbar-secondary-height);
  border-bottom: 1px solid var(--gin-border-color-secondary);
  box-sizing: border-box;
}
```

When I disable the line `height: var(--gin-toolbar-secondary-height);` in my browser dev tools, the issue is fixed for me. When I enable it again, the height of the element is `0` (zero).

---

**Screenshot:**

<img src="https://github.com/backdrop-contrib/gin/assets/14188307/78404312-3acf-4b2b-8d8b-dda06e3f845d" width="480">

**Comment by laryn** [comment]
Good catch -- I think in Drupal the defaults were all set to zero to make them easier to set based on the menu/nav style chosen, but since we don't have multiple nav styles to choose from at the moment in Backdrop, it threw things off a bit. I've made a fix for now.
