### ISSUE TITLE
Table headers

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#12]
## Drupal Gin: 
![image](https://github.com/backdrop-contrib/gin/assets/871421/88849a4c-27b8-4c8a-a300-842110e5aa76)

## Current Backdrop Gin:
![image](https://github.com/backdrop-contrib/gin/assets/871421/7be5ef1e-7063-4e91-b75a-50d423718715)

**Comment by laryn** [comment]
Re-opening after reverting the name to Gin.

**Comment by yorkshire-pudding** [comment]
Images have disappeared above but perhaps you're referring to the same issue I noticed:

![image](https://github.com/backdrop-contrib/gin/assets/20357797/6430c959-8915-40fd-8b30-e273ebeaaea2)

Namely, that headers are centred even though contents are left aligned.

**Comment by laryn** [comment]
## Gin/Drupal:

![image](https://github.com/backdrop-contrib/gin/assets/871421/0bf2a919-c7d6-434f-86d9-b0b2b1c6f15f)


## Gin/Backdrop:

![image](https://github.com/backdrop-contrib/gin/assets/871421/da0e56c2-f47d-44b8-9b6a-029734533432)
