### ISSUE TITLE
Broken menu search icon in admin bar

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/gin#123]
This is what I see in a Backdrop demo of core 1.27.1 and Gin 3.0.0-beta-1:
<img width="475" alt="image" src="https://github.com/backdrop-contrib/gin/assets/2423362/914db086-3afa-4d89-8da3-29481b296c32">

**Comment by laryn** [comment]
Thanks @klonos -- which browser? I don't see that in Firefox but will try to test with Chromium as well.

**Comment by laryn** [comment]
@klonos Verified in Chromium. Care to test the PR?
