### ISSUE TITLE
In admin views page put options in modal window, not at the end of the page

### ISSUE THREAD

**Issue by fcalzado** [backdrop-contrib/gin#129]
In admin views page would be nice to put options in modal window (like with the default "Seven" admin theme, and not at the end of the page.

**Comment by laryn** [comment]
@fcalzado Thanks! Can you add a screenshot of what you're referring to in Seven, and one of how it is looking currently in Gin?

**Comment by fcalzado** [comment]
@laryn Sure
This is how you can configure an option in a view in the Seven theme:
![Screenshot_20240501_211736](https://github.com/backdrop-contrib/gin/assets/39213911/0e29b7b5-c029-40f1-bff8-0cbb436b0fe6)
This is how you can configure the same option in a view in Gin:
![Screenshot_20240501_212007](https://github.com/backdrop-contrib/gin/assets/39213911/bd12d916-bf87-47b6-9804-fed3eac2b89e)

**Comment by laryn** [comment]
@fcalzado

Whoa, that looks a lot different than what I see (screenshot in dark mode):
 
![CleanShot 2024-05-01 at 14 36 54@2x](https://github.com/backdrop-contrib/gin/assets/871421/6fa60b3f-415e-4f7d-9f66-f9832193f591)

Can you replicate this on [a demo site](https://backdropcms.org/demo)? Is it possibly a combination of settings, or a contrib module that you have and I don't, or... ? Any errors in the console? Any errors in the log? Which version of Gin do you have active?

**Comment by laryn** [comment]
Please reopen if you can replicate on a fresh site or have further information.
