### ISSUE TITLE
Settings: Option to render checkbox as a toggle switch

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#13]
This probably makes sense as a theme setting.

![image](https://github.com/backdrop-contrib/tonic/assets/871421/5932fd23-aeda-4da5-911b-2551c9d5a510)

Follow up from https://github.com/laryn/tonic/issues/8

**Comment by saschaeggi** [comment]
Has been migrated with https://github.com/backdrop-contrib/gin/commit/7a94f085758730f9799133859531ba99b158194b
