### ISSUE TITLE
Style for overridden status in Views headings doesn't apply

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#130]
Like the _Seven_ admin theme, _Gin_ provides a style for the `h3` heading of overridden Views configuration sections (Format, Fields, Filter criteria, etc.):

```
.views-ui-display-tab-bucket.overridden > h3 {
  font-style: italic;
}
```

The style doesn't apply in _Gin_, because the child selector doesn't work, as there is an additional wrapper element around the `h3`:

```
<div class="views-ui-display-tab-bucket fields overridden views-ui-display-tab-bucket" title="Overridden">
  <div class="views-ui-display-tab-bucket__header">
    <h3 class="views-ui-display-tab-bucket__title">Fields</h3>
  </div>
...
```

**Comment by laryn** [comment]
@olafgrabienski Can you provide a screenshot?

**Comment by olafgrabienski** [comment]
Sure, below two screenshots, the first is from Gin, the second from Seven (where the `h3` is in italics).

<img src="https://github.com/backdrop-contrib/gin/assets/14188307/4974742a-4d90-4fa9-8648-24dd10ffae9f" width=600>

---

<img src="https://github.com/backdrop-contrib/gin/assets/14188307/e62cb877-74b2-457b-8f0f-91056fbc70da" width=600>

**Comment by laryn** [comment]
Thanks @olafgrabienski -- I hadn't ever noticed that before!
