### ISSUE TITLE
If making Gin default theme - generates error

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/gin#133]
Steps to Reproduce

1) Add Gin to site
2) Enable and set to default (Not something you are likely to do on purpose, but something that is easy to accidentally do)
3) Visit home page

When Gin is set as the default site, if you try to visit a page you get this fatal error. I recognize that GIN is not designed to be a front end default theme, but it's easy to make this mistake and I would expect a more graceful failure, if failure is inevitable.

`implode(): Argument #1 ($array) must be of type array, string given`

Log shows:

`Warning: Undefined variable $html_classes in include() (line 42 of /var/www/html/themes/gin/templates/page/page.tpl.php).`

`	TypeError: implode(): Argument #1 ($array) must be of type array, string given in implode() (line 42 of /var/www/html/themes/gin/templates/page/page.tpl.php).`

![image](https://github.com/backdrop-contrib/gin/assets/3144571/b4bc5a72-2e53-4d96-a0ed-1c7fffa3d587)

**Comment by laryn** [comment]
@stpaultim Thanks for the report. Can you test the attached PR?

**Comment by stpaultim** [comment]
@laryn This seems to do the trick. I tested with the PR and did not see the problem.
