### ISSUE TITLE
Dark mode always on

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#139]
Using the latest code (downloaded yesterday, 8th of July), after installing and enabling _Gin_ as admin theme, the theme gets displayed all the time in dark mode, no matter if the setting is _Light_, _Auto_ or _Dark_. The settings get saved (I've checked the configuration file), but the class `gin--dark-mode` keeps staying in the `<html>` tag.

PS: Switching between Light, Auto and Dark, _sometimes_ the theme appeared for a while in light mode. It changed however back to dark mode when I clicked "Save".

**Comment by laryn** [comment]
@olafgrabienski Can you check the latest code to make sure it fixes for your case as well? I was able to replicate and the code I just pushed fixed it for me.

**Comment by olafgrabienski** [comment]
@laryn Thanks for the update! Updating to the latest code didn't fix the site where I noticed the issue (cleared caches several times). However, the same code works as expected on another site where I hadn't installed _Gin_ before.

**Comment by laryn** [comment]
@olafgrabienski Can you provide any further information about the site that this didn't help on?

**Comment by olafgrabienski** [comment]
@laryn Not sure, I'll have a look in the next days. It's however a general test site and as such not important to fix.

**Comment by olafgrabienski** [comment]
@laryn Today I had another look at my test site. After clearing caches and enabling _Gin_ (I had switched to _Seven_ in the meantime), the "Appearance" modes (Light, Auto, Dark) now work as expected. 🎉
