### ISSUE TITLE
Broken "Search" icon in autocomplete fields

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/gin#140]
This is with the latest 1.x-3.0.0-beta-4 on Backdrop 1.28.2:

<img src="https://github.com/user-attachments/assets/bd387f95-91f5-4f38-b9c9-008ed86aa24a" width=60%>

**Comment by laryn** [comment]
This seems to have been fixed along the way:
![CleanShot 2024-09-13 at 22 28 44@2x](https://github.com/user-attachments/assets/9586a6b2-b6d4-4636-8071-b04caa5bd444)
