### ISSUE TITLE
Admin Bar: Menu search: Actual menu items not highlighted when revealed

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/gin#141]
The admin bar has a neat "menu search" functionality, where as you start typing, results with the matching names of various menu items are shown. As you hover the mouse over these items in the search results, the actual menu is revealed. However, these menu items aren't highlighted in Gin, which makes it difficult to distinguish from the rest of the menu items.

**Comment by laryn** [comment]
Fixed: 
![CleanShot 2024-09-13 at 22 17 42@2x](https://github.com/user-attachments/assets/147b07a9-7ce5-462d-87cc-1d3d70e4a1e3)
