### ISSUE TITLE
Dialogs not working on text format page

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/gin#30]
Steps:

1. Go to `admin/config/content/formats/filtered_html`
2. Click on any config button

Expected result:
dialog opens

Actual result:
Something appears to happen but dialog doesn't open (FPS on gif recorder to low to capture)

![chrome_8TcAEv54Kh](https://github.com/backdrop-contrib/gin/assets/20357797/4e3fc7cb-79c4-497a-986e-a29e57d5bea5)

**Comment by laryn** [comment]
@yorkshire-pudding  Anything in the console?

**Comment by yorkshire-pudding** [comment]
Didn't think to check that. I'll check in the morning

**Comment by saschaeggi** [comment]
Fix incoming with Migration Part 3.

**Comment by saschaeggi** [comment]
Fixed with be81c4f

**Comment by yorkshire-pudding** [comment]
Thanks @saschaeggi - Fix confirmed
