### ISSUE TITLE
Layout block administration styling

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#31]
The layout block add pages and the flexible layout design pages aren't yet looking satisfactory.

**Comment by laryn** [comment]
@docwilmot  I'm not by the computer at the moment. Can you add some screenshots?

**Comment by docwilmot** [comment]
![Screenshot 2023-07-04 152135](https://github.com/backdrop-contrib/gin/assets/1042283/ef9cf0b0-f0a6-4550-9328-4c0ec026cdbb)
![Screenshot 2023-07-04 152209](https://github.com/backdrop-contrib/gin/assets/1042283/9ca894b2-91e5-4b7c-89b9-4ba689984c3e)

**Comment by docwilmot** [comment]
Actually, the modal opens below the page content! ( Clicked the link to add a field)

![fullscreenpage](https://github.com/backdrop-contrib/gin/assets/1042283/19a75942-a752-44ff-8923-bda502bb2571)

**Comment by laryn** [comment]
It's not complete yet but I made some minor tweaks in the Backdrop overrides:
![image](https://github.com/backdrop-contrib/gin/assets/871421/2ab8d3a8-c58f-4145-bd5a-42afa083d420)

Dropbuttons are already noted as a separate issue; I realize they are ugly at the moment. And it may not need to look identical in Backdrop, but for reference, here's how Layout Builder is shown in Gin on Drupal 10:

![image](https://github.com/backdrop-contrib/gin/assets/871421/64a2b736-57ba-47a6-b715-97530c026b1c)

I think the dashed outlines could be more prominent in the current Backdrop version.

**Comment by docwilmot** [comment]
This page looks good now. I agree the design could use a little tweaking to look more Gin and less Seven, but no glaring errors now.

**Comment by laryn** [comment]
@saschaeggi On second look, the D10 Layout Builder screenshot I added is not really Gin styling but rather Drupal core. Are there examples of a layout editing interface that are styled in Gin, or is this a new type of feature for Gin?

**Comment by laryn** [comment]
I'm going to close this one for now.

Here's the current status (this is a flexible layout editor screen):
![image](https://github.com/backdrop-contrib/gin/assets/871421/40f56fa9-11ba-4ccb-a056-d95ba0a5f9ce)
