### ISSUE TITLE
Dialog close button [ X ] is not reachable

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#34]
On my local the dialogs are partly hidden below the Admin Bar and I cant get to the X to close them.

![Screenshot 2023-07-04 154907](https://github.com/backdrop-contrib/gin/assets/1042283/247dce37-026d-469a-a9e4-47a4824f84d0)

**Comment by laryn** [comment]
@docwilmot Can you test with the latest? I'm not seeing this:

![image](https://github.com/backdrop-contrib/gin/assets/871421/5903908a-a24d-4609-a01b-05df259d75c5)

**Comment by docwilmot** [comment]
Unfortunately yes.
![Screenshot 2023-07-30 132023](https://github.com/backdrop-contrib/gin/assets/1042283/3769c322-136c-447a-aae4-fa4ecfb826d0)

But I've just realised as well there is some issue with the z-index going on here because in the image above the page title (the bit that says "Home page") and the breadcrumb actually are *above* the modal overlay (the breadcrumb is actually clickable while the modal is active), which is what is actually interfering with the ability to click the X.

Also, was going to make another issue but maybe the page title *block* (or pseudo-block, whatever) is caught in the same z-index issue as seen below.

![Screenshot 2023-07-30 132147](https://github.com/backdrop-contrib/gin/assets/1042283/0d9f9078-46bd-46ce-9444-e8225cb91d55)

In this one when scrolling up, the page title block gets "fixed" with the page title.
![Screenshot 2023-07-30 132122](https://github.com/backdrop-contrib/gin/assets/1042283/acc4ef1e-6265-42ab-badb-17e73a3867fb)

**Comment by laryn** [comment]
@docwilmot Can you test the latest again? Hopefully it's somewhat better, if not complete.

**Comment by docwilmot** [comment]
Progress! For tall dialogs like the first image in https://github.com/backdrop-contrib/gin/issues/34#issuecomment-1657238866 the dialog's X is still partly hidden under the Admin bar but now it is clickable. I suspect dialogs need a max height relative to the viewport.

**Comment by laryn** [comment]
@docwilmot I made one more minor z-index adjustment.

**Comment by docwilmot** [comment]
yep that did it. LGTM
