### ISSUE TITLE
The AJAX loading spinner appears within dropbuttons

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#39]
In Seven, clicking and AJAX link in the layout page causes the spinner to appear just below the dropbutton, but in Gin, the dropbutton expands below and the spinner appears within the dropbutton

Furthermore on flexible layout, clicking the configure button shows the dropbutton expanding *below* the pseudoblock. 
![below](https://github.com/backdrop-contrib/gin/assets/1042283/dc76c482-6dfc-4d45-8e95-107f59a6567c)

**Comment by laryn** [comment]
@docwilmot I'm not saying this is a good thing, but I see the same on Seven:

![CleanShot 2024-03-25 at 08 57 26@2x](https://github.com/backdrop-contrib/gin/assets/871421/f9a3ba13-d19b-4896-a329-26f3fa963a0f)

**Comment by laryn** [comment]
I think this is a core issue (and I think I may have a fix for it). Moving conversation to https://github.com/backdrop/backdrop-issues/issues/6441
