### ISSUE TITLE
Fix formatting options fieldset 

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#44]
![Screenshot 2023-08-09 145144](https://github.com/backdrop-contrib/gin/assets/1042283/4cc669f6-2d95-4eed-b296-a8bb9ee077c1)

**Comment by laryn** [comment]
Fixed in https://github.com/backdrop-contrib/gin/commit/19a2684a392e335598792b4457a6ef5645346bad

**Comment by laryn** [comment]
![image](https://github.com/backdrop-contrib/gin/assets/871421/d281f50a-5434-400a-b04a-aaca9988583f)
