### ISSUE TITLE
Fix spacing on vertical tabs

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#45]
Needs some spacing at the top (ie above "Publish action" in the image below), and a bit of spacing between individual items in the tab

![Screenshot 2023-08-09 145144](https://github.com/backdrop-contrib/gin/assets/1042283/ba078648-5190-454e-adc8-707d6fa44acd)

**Comment by docwilmot** [comment]
Also the Vtab main labels (eg "URL settings" above) are too similar to the subheader below it (eg "Automatic alias")

**Comment by laryn** [comment]
@docwilmot I believe this is moot after https://github.com/backdrop-contrib/gin/issues/21 but let me know if not!
