### ISSUE TITLE
Textareas need consistent styling

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#46]
![Screenshot 2023-08-09 150433](https://github.com/backdrop-contrib/gin/assets/1042283/85c1e9f9-c09e-4674-8bbd-7a2d23d6a98a)

On the content edit form textarea has nice rounded corners etc. Once you switch to Plain HTML though, you get a plain square angled box, like the one above. Same for all other textareas.

**Comment by laryn** [comment]
I've made a few tweaks:

![image](https://github.com/backdrop-contrib/gin/assets/871421/cb299414-fa29-4de7-ba8d-8901abdfaa8c)

![image](https://github.com/backdrop-contrib/gin/assets/871421/5c5ea576-813d-4062-bf0f-283a476a60d0)
