### ISSUE TITLE
Choose region widths dialog needs some help

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#49]
![image](https://github.com/backdrop-contrib/gin/assets/871421/c3437b65-6587-447b-822d-1d7afe288f7d)

**Comment by docwilmot** [comment]
FYI the choose region widths dialog is based on the same CSS/JS that does the clickable layout icons in layout configure forms. So as expected, the UI for the icons there are broken too.

**Comment by laryn** [comment]
Thanks @docwilmot -- I made some adjustments here.

![image](https://github.com/backdrop-contrib/gin/assets/871421/be109117-c990-46eb-a7d4-f8a5cd5e5cc5)

![image](https://github.com/backdrop-contrib/gin/assets/871421/302cb913-cbb5-4be5-8631-c5149c9c616c)
