### ISSUE TITLE
Menu Link Weight and Experimental Sidebar on edit form Error

### ISSUE THREAD

**Issue by mrlch** [backdrop-contrib/gin#55]
Yeah, I love to see gin on backdrop. 

When I was trying the Experimental Feature "Sidebar on edit form" I got the following error when used with the Menu Link Weight Module:

> Argument 1 passed to _menu_link_weight_get_parent_value_from_element() must be of the type array, null given, called in */modules/menu_link_weight/menu_link_weight.module on line 109

Thank you.

**Comment by laryn** [comment]
@mrlch Thanks for testing and reporting! Do you feel comfortable trying the latest dev? There's one commit that isn't in a release yet and I'm curious if it makes any difference.

**Comment by mrlch** [comment]
Yes, were I can get the dev-version?

**Comment by laryn** [comment]
@mrlch, you can `git clone` or `git pull` from the `1.x-3.x` branch of the repo, or download a Zip of the latest dev from the repo's main page:

![CleanShot 2023-09-11 at 10 27 01@2x](https://github.com/backdrop-contrib/gin/assets/871421/9e9b0a1f-8df6-4916-b880-ea78da2b72b9)

**Comment by mrlch** [comment]
Thank you. 

with this version the error-message is gone. 

But when I try to add a Link to the menu and sort it with drag and drop, The sidebar jumps always to the top. As soon as I try to change the order. Maybe it's also a problem with the paragraph-module on this particular installation. 

I'll check it further and report later.

**Comment by laryn** [comment]
@mrlch Ready for another try?

**Comment by mrlch** [comment]
yes. I'll let you know.

**Comment by mrlch** [comment]
With this release the section is shown below the content edit form and not as a sidebar. 

![Bildschirmfoto 2023-09-12 um 07 46 53](https://github.com/backdrop-contrib/gin/assets/16351448/fc2133fb-c4ca-4322-9e50-2468e37ce58b)

With both versions I have the problem, that as soon as a try to rearrange the navigation, the whole section is duplicated.
Here a Screenshot from the previous version. 

![Bildschirmfoto 2023-09-11 um 20 17 48](https://github.com/backdrop-contrib/gin/assets/16351448/9ac7cd95-f382-4be2-8b74-babc335d7411)

**Comment by laryn** [comment]
@mrlch When you got the latest dev most recently, did you clear caches?

**Comment by mrlch** [comment]
@laryn yes. I'll later make some tests on a fresh installation were I add modules incrementally to check the behaviour.

**Comment by mrlch** [comment]
@laryn Good news: a fresh install and everything looks good and functions well. 

the steps I took:
1. Installation of Backdrop
2. Clone and installation of gin with git clone
3. Changing admin theme and settings.
4. First Testing without menu link weight -> was working well
5. Installing menu link weight via gui and testing -> everything was working well
6. Installation of Paragraphs and testing -> everything ok.

![Bildschirmfoto 2023-09-12 um 16 19 34](https://github.com/backdrop-contrib/gin/assets/16351448/dadf75e4-6ed9-4a8f-800a-9dce3e9d0b0d)


I'll later check out with more modules and two languages.

**Comment by mrlch** [comment]
@laryn 
I think we can close this issue. I was making some tests with another mature installation. And everything runs well. 
It seems to me, that in the problematic installation it's a problem with another module. 
If I find out what's the problem I can open a new issue. 

thank you so much for your fast response and your awesome work.

**Comment by laryn** [comment]
Sounds good @mrlch -- thanks for testing!
