### ISSUE TITLE
Sidebar panel toggle button

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#56]
I've added the sidebar toggle button in https://github.com/backdrop-contrib/gin/commit/fe5d8090dc15a31d3584cdfdc6991a004b34b654

@mrlch Are you interested in testing?

**Comment by mrlch** [comment]
@laryn I tested it on two different installations (the fresh and the more developed one). My first impression is that it works great.

**Comment by laryn** [comment]
Awesome, I'll close this then and we can open specific tickets if there are any specific issues found.

Are you coming to Backdrop Live @mrlch? Specifically thinking of this session:
https://events.backdropcms.org/discussions/backdrop-live-september-2023/introducing-gin-for-backdrop

**Comment by mrlch** [comment]
Yes I think we can proceed like this. 

I'll make an a mark in my calendar for the Backdrop-Live Event. But I can't guarantee to be there.
