### ISSUE TITLE
Error: Call to undefined function _gin_accent_radios() in form_builder()

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/gin#62]
When Gin theme is enabled but not set as the admin theme going to the gin settings, /admin/appearance/settings/gin results in error:
```Error: Call to undefined function _gin_accent_radios() in form_builder() (line 1988 of ...\core\includes\form.inc). ```
This continues to occur even after ensuring caches have been flushed.

**Comment by laryn** [comment]
Thanks @izmeez!
