### ISSUE TITLE
Adjust top banner position if Admin Bar Menu "Keep bar at top of page" turned off

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/gin#63]
If the Admin Bar Menu setting "Keep bar at top of page" is turned off there is visible space above the page header. Also if the setting is turned on there appears to be a space of possibly 1 px.
![bd-gin-theme-admin-bar-menu-keep-at-top-off](https://github.com/backdrop-contrib/gin/assets/6208775/ed3adbb4-341b-4e14-83f2-d4660111a95d)
![bd-gin-theme-admin-bar-menu-keep-at-top-on](https://github.com/backdrop-contrib/gin/assets/6208775/c171a641-785a-43db-92b8-32b5fcc18847)

**Comment by laryn** [comment]
Thanks @izmeez!

**Comment by izmeez** [comment]
Confirmed fixed in latest dev. Thank you.
