### ISSUE TITLE
Horizontal check boxes and radio buttons not aligned with labels

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/gin#64]
I'm not sure if this is an issue for the module_filter module or the gin theme. With the gin theme the horizontal check boxes are not aligned with the labels but with the seven theme they are.
![bd-gin-theme-module-filter-horizontal-check-boxes-not-aligned-with-labels](https://github.com/backdrop-contrib/gin/assets/6208775/fe3045e7-5218-4418-8a15-210bf228d7bd)
![bd-seven-theme-module-filter-horizontal-check-boxes-aligned-with-labels](https://github.com/backdrop-contrib/gin/assets/6208775/a8a8c2e0-7fc3-4742-937f-4e2eccc66b05)

**Comment by laryn** [comment]
I have to do a little further testing, but removing this `float: left` may be enough (as long as it doesn't mess anything else up):

 - https://github.com/backdrop-contrib/gin/blob/1.x-3.x/styles/base/_form.scss#L181

Also noting, however, that this module implements some kind of "switch" styling that should be overridden with Gin's boolean switch.

**Comment by izmeez** [comment]
It's also like that on the available updates page, so maybe removing the float may be enough.
![bd-gin-theme-available-update-horizontal-radio-buttons-not-aligned-with-labels](https://github.com/backdrop-contrib/gin/assets/6208775/f062739f-d4df-4e63-a0f5-d6341cd5e420)

**Comment by laryn** [comment]
This should be fixed in the latest dev and in the next release. Thanks!

**Comment by izmeez** [comment]
Confirmed it is fixed in the latest dev, thank you.
