### ISSUE TITLE
Don't move action option off to right side

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/gin#66]
I appreciate this is a question of design aesthetics and others may view it differently. Personally, I do not like the way the Gin theme moves action options over to the right top corner. I find it disruptive to the normal flow, requiring scanning away from the current point of focus. Attached are screenshots of how the seven theme maintains the flow and how the gin theme changes the flow.
The Seven theme:
![admin-seven-create-button](https://github.com/backdrop-contrib/gin/assets/6208775/9b05b338-9bb3-4db5-8b78-1b13c102ad07)
The Gin theme:
![admin-gin-create-button](https://github.com/backdrop-contrib/gin/assets/6208775/b5a88a74-3322-4e47-affb-6df83c764ab0)

**Comment by laryn** [comment]
@izmeez I wonder if it's a matter of getting used to it. I really appreciate these local action links being in a consistent place but also fixed when scrolling long pages so they are always readily accessible.

**Comment by izmeez** [comment]
I guess you can't please everyone, unless maybe you have a setting option. I just wanted to share my thought and appreciate hearing yours with reference to long pages. Who knows, you may be right, it may grow on me?
