### ISSUE TITLE
Broken horizontal tab menus on smaller screens

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/gin#67]
I'm not sure if this is a deliberate design change or not. However, the Gin theme does not really have distinctive horizontal tab menus and on a small screen this appearance is lost and shows as options. This does not preserve the context as well as tabs do. Here are screen captures of small screens to illustrate.
The Seven theme with a small screen:
![admin-seven-small-screen](https://github.com/backdrop-contrib/gin/assets/6208775/1e942e0c-0c8b-4f76-a594-b9f5ee60fd05)
The Gin theme with a small screen:
![admin-gin-small-screen](https://github.com/backdrop-contrib/gin/assets/6208775/7d3d6ef0-4a27-4244-ba95-15c91abbd3d1)

**Comment by laryn** [comment]
Agreed, something's not good here. Comparison screenshots:

------------
# Seven

![CleanShot 2024-03-27 at 15 09 42@2x](https://github.com/backdrop-contrib/gin/assets/871421/1b510ded-9692-4bc9-9848-b483c6a613cc)

![CleanShot 2024-03-27 at 15 10 17@2x](https://github.com/backdrop-contrib/gin/assets/871421/e2e071e9-b8cd-4c75-91f7-e8ec9431e351)


-------------
# Gin Drupal

![CleanShot 2024-03-27 at 15 12 11@2x](https://github.com/backdrop-contrib/gin/assets/871421/9885d1f7-607a-4043-9d65-30e763a17566)

![CleanShot 2024-03-27 at 15 13 33@2x](https://github.com/backdrop-contrib/gin/assets/871421/60ce61e4-e2e2-440d-b388-646f63c950c0)

-------------
# Gin Backdrop

![CleanShot 2024-03-27 at 15 07 48@2x](https://github.com/backdrop-contrib/gin/assets/871421/e7174f2a-2901-423f-ae4a-6f6a8e62df60)

![CleanShot 2024-03-27 at 15 08 51@2x](https://github.com/backdrop-contrib/gin/assets/871421/bce4b2fa-b5d6-41d6-b7e6-695110a77655)

![CleanShot 2024-03-27 at 15 09 10@2x](https://github.com/backdrop-contrib/gin/assets/871421/35c7f8c0-feb7-4343-a4a2-817c758c12e5)

**Comment by laryn** [comment]
@izmeez Are you able to test the linked PR? I'm departing somewhat from the Gin Drupal styles here (which actually may be more like Claro styles) and sticking to the responsive pattern Backdrop added to Seven, with the tabs hiding and expanding with the three dot pattern:

https://github.com/backdrop-contrib/gin/assets/871421/8b464d41-683d-4b6a-8b41-8c92647d87bb
