### ISSUE TITLE
Core compatibility of messages

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/gin#68]
Demo contrib module styles messages by applying a ```messages``` class and the type of message as another class (```status```, ```warning```, or ```error```). This comes from the messages.them.css core file. I guess many other contrib modules use this ([paragraphs does](https://github.com/backdrop-contrib/paragraphs/blob/b7f3f97804f46b3bfe6a6e8d1fca6a636c4085c6/paragraphs.admin.inc#L492), for instance). This use of core classes produces a very ugly message element in Gin:

![Esteu_segur_que_voleu_reemplaçar_la_instantània_ja_existent_Gin____Robert_-_Backhub](https://github.com/backdrop-contrib/gin/assets/105581/9aa28c2f-d1fc-48e2-8585-49649c12d2b3)

![Esteu_segur_que_voleu_reemplaçar_la_instantània_ja_existent_Gin____Robert_-_Backhub](https://github.com/backdrop-contrib/gin/assets/105581/b15c58c6-3f50-42fb-b2ba-d724f00fe326)

![Cursor_and_Esteu_segur_que_voleu_reemplaçar_la_instantània_ja_existent_Gin____Robert_-_Backhub](https://github.com/backdrop-contrib/gin/assets/105581/5f7559bc-aebc-43de-b81e-95f9e8cba373)

Gin produces the right messages by applying the following classes:

```
messages messages--status
messages messages--error
messages messages--warning
```

Wouldn't it be nice to add a core compatibility to show the same gin messages with:

```
messages status
messages error
messages warning
```

**Comment by laryn** [comment]
Thanks @robertgarrigos -- are you on the latest version of Gin? Here's how some of the Demo messages look when I install it:

![CleanShot 2023-10-02 at 17 07 19@2x](https://github.com/backdrop-contrib/gin/assets/871421/50f8b9a8-2180-476a-accc-cf28645fd910)

**Comment by robertgarrigos** [comment]
mmmm yes, I have the latest version of Gin, but I see it like this:

<img width="153" alt="Are_you_sure_you_want_to_reset_the_site____Robert_-_Backhub" src="https://github.com/backdrop-contrib/gin/assets/105581/51294830-a956-481e-b839-e348b9579e9c">

?!

**Comment by laryn** [comment]
@robertgarrigos I am also having trouble reproducing this one! Can you provide steps?

**Comment by robertgarrigos** [comment]
Sorry, I can't. It is working fine now. The only thing I have done is updating backdrop during this time. I don't know what was going on.
