### ISSUE TITLE
error with autocomplete fields

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/gin#69]
I'm having an issue with autocomplete fields, in this case with node reference: depending on which position are in the node creation/edit form, suggestions are missing. When the autocompleted field is near the top of the form, the suggestions list appears normally. When the field is near the bottom because other fields are before, the suggestion’s list is missing. I tried with the same field, just put in a different position within the form.

<img width="326" alt="Incidència___ERP" src="https://github.com/backdrop-contrib/gin/assets/105581/dc171a8e-e5e0-41c5-a0fa-883a3fcc8b4d">

<img width="328" alt="Crea_Incidència___ERP" src="https://github.com/backdrop-contrib/gin/assets/105581/d2a671b3-505b-4350-ba7a-d5b584c03136">

<img width="322" alt="Incidència___ERP" src="https://github.com/backdrop-contrib/gin/assets/105581/df6dd02a-611e-4ead-92ab-8f58dedcea32">

<img width="213" alt="Crea_Incidència___ERP" src="https://github.com/backdrop-contrib/gin/assets/105581/8f7ae237-0e89-4730-9c36-6a7830b307f3">

Switching to Seven fixes the problem.

**Comment by laryn** [comment]
@robertgarrigos I'm having trouble reproducing this with the core `Entity Reference` or the contrib `References` module. Can you provide steps to reproduce?

**Comment by robertgarrigos** [comment]
Looking into this because I'm having this problem with a particular site, but not on my local testing site. It might be an incompatibility with a contrib module.

**Comment by robertgarrigos** [comment]
Found the problem: incompatibility with jquery update contrib module set to use jquery 2.2. No problem with jquery 1 or 3.

With jquery 2.2 the div with id='autocomplete' gets printed within the parent div of the autocomplete field instead of as first div right after the opening body html tag.

**Comment by laryn** [comment]
Wow, I didn't even know we had a jQuery update for Backdrop! With core offering the old 1.x branch as well as the latest 3.x branch, which both seem to work according to your testing, I think this is not a high priority bug. Do you agree? Or are you unable to switch to jQuery 3.x?

**Comment by robertgarrigos** [comment]
I just switched to 3.x. Let's see how it goes ;-) thanks!

**Comment by laryn** [comment]
Sounds good. Please reopen if necessary -- closing for now.
