### ISSUE TITLE
Admin menu

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#7]
1. On very small widths, the menu doesn't fully collapse into mobile mode and obscures the page.
2. I wonder if we might be able to provide the current menu (roughly equivalent to "Horizontal, Modern Toolbar") and a vertical version of the same (roughly equivalent to "New Drupal Navigation, Test integration") 

![CleanShot 2024-01-09 at 22 44 32@2x](https://github.com/backdrop-contrib/gin/assets/871421/63f9b669-c6cb-4fdf-9a4d-0ebfebe458cd)

**Comment by laryn** [comment]
Re-opening after reverting the name to Gin.

**Comment by saschaeggi** [comment]
Added initial styling in f6a93ef

**Comment by laryn** [comment]
If we are interested in providing the same options as Gin for Drupal has in terms of the menu settings/orientation, perhaps it could be dependent on and integrate with the Navbar module: https://backdropcms.org/project/navbar

**Comment by laryn** [comment]
I wonder if we might be able to provide the current menu (roughly equivalent to "Horizontal, Modern Toolbar") and a vertical version of the same (roughly equivalent to "New Drupal Navigation, Test integration") 

![CleanShot 2024-01-09 at 22 44 32@2x](https://github.com/backdrop-contrib/gin/assets/871421/63f9b669-c6cb-4fdf-9a4d-0ebfebe458cd)

**Comment by laryn** [comment]
I'm adding a bit of an overhaul to the default admin menu which strips out the core admin menu styles and pulls back in with a lot of it stripped out (background images, colors, etc.)

![CleanShot 2024-03-28 at 12 28 59@2x](https://github.com/backdrop-contrib/gin/assets/871421/a535ebe9-ddd5-4c42-b68d-eea8820e682f)

![CleanShot 2024-03-28 at 12 29 21@2x](https://github.com/backdrop-contrib/gin/assets/871421/ad50cf84-063a-4c63-aa08-98a81ff1e8e1)

https://github.com/backdrop-contrib/gin/commit/272552315c0d84a30b72a71bf75d489a75c651fc

**Comment by olafgrabienski** [comment]
Looks nice ... as long as I don't switch to the frontend! Is this already supposed to work with [Tonic](https://github.com/backdrop-contrib/tonic)?

**Comment by laryn** [comment]
> Is this already supposed to work with [Tonic](https://github.com/backdrop-contrib/tonic)?

Hopefully soon!

**Comment by klonos** [comment]
@laryn the title of this issue is generic and the original screenshot added to the issue summary is broken/missing. Can you please clarify the goals/scope of this issue when you get a chance?

**Comment by laryn** [comment]
@klonos At this point it's to assess whether we can offer an additional option that is more like one of the vertical options provided in Drupal. And I just noticed on very small widths the menu misbehaves.

**Comment by klonos** [comment]
Thanks for taking the time to clarify @laryn 🙏🏼 ...do you mind if we update the issue title to reflect that, or prefer to leave it generic/vague for now?

**Comment by laryn** [comment]
@klonos I decided to break these into their own issues and consider this early-in-the-porting-process issue as complete.

See:
 - https://github.com/backdrop-contrib/gin/issues/145
 - https://github.com/backdrop-contrib/gin/issues/144
