### ISSUE TITLE
Appearance page theme links need clear fix

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/gin#70]
![Screenshot 2023-11-03 214409](https://github.com/backdrop-contrib/gin/assets/1042283/edf9ec68-105e-4a12-918b-b30df2192987)

**Comment by docwilmot** [comment]
Only at intermediate widths: 1280 to about 1798px

**Comment by laryn** [comment]
On mobile it also needs some adjustment on the links, as well as using stacking instead of columns (and not stretching the image):
![CleanShot 2023-11-04 at 11 03 21@2x](https://github.com/backdrop-contrib/gin/assets/871421/825b6b47-f3bd-4aa3-8f30-76db9afa5952)

**Comment by laryn** [comment]
@docwilmot Whoops, closed automatically -- can you test that commit and reopen if it's still an issue?

**Comment by docwilmot** [comment]
I'm still getting a mess between 970 - 1130px

**Comment by docwilmot** [comment]
Actually above that width as well. Using chrome inspector device emulation by the way (see dimensions at top of image).

![Screenshot 2023-11-04 205439](https://github.com/backdrop-contrib/gin/assets/1042283/f48afc24-c321-4147-ae73-b00933e22dd6)
![Screenshot 2023-11-04 205108](https://github.com/backdrop-contrib/gin/assets/1042283/d7174fe7-ce57-4007-8496-2f895bee32fc)

**Comment by laryn** [comment]
I'll have to test more thoroughly with Chrome. Here's what I see (Firefox):

![CleanShot 2023-11-04 at 22 44 34@2x](https://github.com/backdrop-contrib/gin/assets/871421/fc31ce53-6ca9-4da3-b11f-7b57dbf656ca)

![CleanShot 2023-11-04 at 22 45 34@2x](https://github.com/backdrop-contrib/gin/assets/871421/ba80dcab-1b53-4d1e-bceb-2857e3529518)

**Comment by laryn** [comment]
@docwilmot Care to try one more time on the latest?

**Comment by docwilmot** [comment]
Looks perfect now.
