### ISSUE TITLE
Better visuals on Views Display Menu Tabs

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#73]
I want to improve the Views Display Menu Tabs to communicate more information without having to click into each one. Right now we have rudimentary visual (strikeout) to show a display is marked for deletion but nothing to show if a display is disabled for example:

![CleanShot 2023-11-17 at 11 21 17@2x](https://github.com/backdrop-contrib/gin/assets/871421/6064b877-5acd-4955-a0a0-bbca0ec32c2b)

**Comment by laryn** [comment]
I've linked a PR for discussion:
![CleanShot 2023-11-17 at 11 19 49@2x](https://github.com/backdrop-contrib/gin/assets/871421/c6891fe4-e045-4e16-bdec-a4735d8909c2)

@saschaeggi Any thoughts on this? Does it introduce clutter or is it helpful?

**Comment by saschaeggi** [comment]
@laryn it does indeed add noise but that doesn't nessessary need to be a bad thing in this case. What I would really avoid is using a cross icon as users are known to this icon as being a remove action in Drupal (& Gin).

**Comment by laryn** [comment]
True. Maybe the strikeout is enough for the deletion indicator.

**Comment by laryn** [comment]
Currently:

![CleanShot 2023-11-17 at 13 19 18@2x](https://github.com/backdrop-contrib/gin/assets/871421/417962cb-d7da-492a-a1ac-4dd699246a03)

**Comment by saschaeggi** [comment]
Way better :+1:

**Comment by saschaeggi** [comment]
Do you want to create a MR upstream for this?

**Comment by laryn** [comment]
@saschaeggi Will do! I'm traveling today so it might not be immediate but it's on my list.

**Comment by laryn** [comment]
[Done](https://www.drupal.org/project/gin/issues/3402619).
