### ISSUE TITLE
Radios and Checkboxes

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#8]
Gin/Drupal converts the radio button to a Boolean Toggle.

**Comment by laryn** [comment]
Re-opening after reverting the name to Gin.

**Comment by saschaeggi** [comment]
Work in progress, part has been addressed with https://github.com/backdrop-contrib/gin/commit/7a94f085758730f9799133859531ba99b158194b

**Comment by laryn** [comment]
Closing for now, feel free to reopen if you wish but I think these are looking great.
