### ISSUE TITLE
Status messages

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/gin#9]
Gin: 
![image](https://github.com/backdrop-contrib/tonic/assets/871421/dcf5e9b9-393a-4370-9b33-e2aaf52e1ed7)

Current:
![image](https://github.com/backdrop-contrib/tonic/assets/871421/81e39580-127e-4f8b-ac4e-b2c3842c13ba)

**Comment by laryn** [comment]
I have to think about this one. I'd like to update the messages style but those Gin messages feel kind of heavy.

**Comment by saschaeggi** [comment]
@laryn I've migrated the ones from Gin in https://github.com/backdrop-contrib/gin/commit/7a94f085758730f9799133859531ba99b158194b as it passes a11y requirements/tests.

But we can also revert this if you want to explore a different direction.

**Comment by laryn** [comment]
Thanks @saschaeggi! Let's leave the Gin styles for now as a11y is obviously a primary concern. We can discuss later if I have something specific to get your feedback on.

**Comment by saschaeggi** [comment]
Alright I'll close this for now then 👍
