### ISSUE TITLE
No sticky header for Permissions matrix

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gin#92]
The sticky header of the Permissions matrix on `admin/config/people/permissions` isn't working. This makes it hard to choose the intended role when enabling or disabling permissions further down on the page.

Steps to reproduce:

1. Go to the Permissions page.
2. Scroll a bit down.

Result: The sticky header with single roles disappears.

---

Screenshots:

**Seven** (Sticky header with roles visible, as expected):

![image](https://github.com/backdrop-contrib/gin/assets/14188307/b34e6eaf-56e3-4b44-bf3a-b2bf1bed3eba)

---

**Gin** (Header with roles hidden by sticky Page title):

![image](https://github.com/backdrop-contrib/gin/assets/14188307/ff08ebfb-558d-4099-a9a3-6671953f3627)

**Comment by laryn** [comment]
Thanks @olafgrabienski! Are you able to test with the latest dev and see if it's already solved? I tested a site running `alpha-6` and I see this, too, but then tested my local dev site and it's working there.

![CleanShot 2024-01-05 at 10 53 05@2x](https://github.com/backdrop-contrib/gin/assets/871421/5414d29c-250c-4f61-98d1-1e5e4ab7a299)

**Comment by olafgrabienski** [comment]
Thanks @laryn, the latest dev works, perfect!

I guess, it was fixed by [an `!important` flag](https://github.com/backdrop-contrib/gin/commit/44df0a69c04a7f3a47c261b160085a7781143d72#diff-d5d856c23139198647405ebf12e92596beb39c9894723fbbaa23eca98103d237R14).
