### ISSUE TITLE
Pager on File Browser

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/gin#95]
I spun up a demo site with dev branch of Backdrop and current release of GIN. This is what the file browser looks like in Seven

![image](https://github.com/backdrop-contrib/gin/assets/3144571/ecfc526a-0542-4705-9b0e-be9406c695bf)

This is what it looks like with Gin

![image](https://github.com/backdrop-contrib/gin/assets/3144571/392d42d2-3aa7-4ffa-b9b9-ba6bcc8587d3)

I'm not sure if the page is supposed to be in the right column. But, even if it was intentional, I don't think it works very well. 

I'd like to see a pager that looks more like we see with Seven. 

Here is a previous issue that has been fixed related to pagers.
https://github.com/backdrop-contrib/gin/issues/72

**Comment by stpaultim** [comment]
I think we should look at the mini-pager as well.

**Comment by laryn** [comment]
Thanks @stpaultim -- I don't think that is intentional. Can you do some testing on mini-pagers and report back here?

**Comment by stpaultim** [comment]
Here is the mini pager in Seven
![image](https://github.com/backdrop-contrib/gin/assets/3144571/2af88ade-ddde-42b9-a650-58082514b309)

Here it is in GIN
![image](https://github.com/backdrop-contrib/gin/assets/3144571/84bb4181-3602-4d69-8c07-68f7f29b5be6)

I ran across this problem, because I was unhappy with the mini-pager in GIN and thought I would try the full page, which it turned out was even worse.

@laryn

**Comment by laryn** [comment]
@stpaultim Turns out it was a pretty simple fix to get that reasonable. What do you think of these:

![CleanShot 2024-01-10 at 17 05 31@2x](https://github.com/backdrop-contrib/gin/assets/871421/79eb1353-4a64-44e7-b6cc-bda2913bdd2a)

![CleanShot 2024-01-10 at 17 06 28@2x](https://github.com/backdrop-contrib/gin/assets/871421/befd2d32-1f90-49c0-a540-610b76171801)

**Comment by stpaultim** [comment]
Looks better. I'll give it a try on my site with more pages. 

@laryn

**Comment by stpaultim** [comment]
@laryn Sorry, but I'm reopening this issue as well. 

The good news is that the full pager looks much better. 
The bad news is that it's broken. 

When I click on a page, on the pager, I go to a blank page. Link is broken somehow.

![image](https://github.com/backdrop-contrib/gin/assets/3144571/a7ef13ea-6d89-42d6-8d35-e3c7e4fcf099)

Is this a problem with the theme or something else?

**Comment by laryn** [comment]
@stpaultim I'm not seeing an issue with the pager functionality on my local -- did you make edits in the Image Library view? Can you try reverting if so, and seeing if it makes a difference?

**Comment by stpaultim** [comment]
@laryn - I'll do some additional experiments and see if I can figure out what is happening. 

I was originally able to reproduce this problem on two sites. One development site we are working on and one fairly clean test site I set up to test CKEditor 5. 

I'll do additional testing now and get back to you.

**Comment by laryn** [comment]
Reopen if this is still an issue.
